# Generated by Django 5.1.1 on 2024-10-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarium_main', '0002_alter_evaluation_name_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10),
        ),
    ]
